### ISSUE TITLE
crashes when loadin applist

### ISSUE THREAD

**Issue by D4NH** [Harv/XLed#7]
crashes when loading the applist at 99% for individual led settings.

**Comment by sillysquid** [comment]
Hi, I have the same issue on my note3.
Tried both the current stable and beta versions.

**Comment by D4NH** [comment]
its because some other xposed mod is bothering it, turning everything off except xled works.

**Comment by sillysquid** [comment]
Ah, ok thanks for the quick response I've been searching for a solution online with no luck.
I will look at the other modules, thanks.

**Comment by sillysquid** [comment]
It appears it was the 3c toolbox plugin.
Works fine now, thanks again.
